# Generated by Django 6.1.1 on 2026-10-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motherprofile",
            name="password",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
