# Generated by Django 6.1.1 on 2026-10-06 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0004_servicebooking_latitude_servicebooking_longitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicebooking",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="servicebooking",
            name="longitude",
        ),
        migrations.AddField(
            model_name="emergencyrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emergencyrequest",
            name="latitude",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="emergencyrequest",
            name="longitude",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="emergencyrequest",
            name="status",
            field=models.CharField(default="Pending", max_length=30),
        ),
    ]
