# Generated by Django 6.1.1 on 2026-10-04 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MotherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=128)),
                ("package", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Cooking Service", "Cooking Service"),
                            ("Home Cleaning", "Home Cleaning"),
                            ("Laundry Service", "Laundry Service"),
                            ("Grocery Delivery", "Grocery Delivery"),
                            ("Nurse Home Visit", "Nurse Home Visit"),
                            ("Doctor Consultation", "Doctor Consultation"),
                        ],
                        max_length=100,
                    ),
                ),
                ("booking_date", models.DateField()),
                ("booking_time", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("note", models.TextField(blank=True)),
                ("status", models.CharField(default="Pending", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="care.motherprofile",
                    ),
                ),
            ],
        ),
    ]
