# Generated by Django 6.1.1 on 2026-10-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0006_paymentrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Cook", "Cook"),
                            ("Cleaner", "Cleaner"),
                            ("Laundry", "Laundry"),
                            ("Grocery", "Grocery"),
                            ("Nurse", "Nurse"),
                            ("Doctor", "Doctor"),
                        ],
                        max_length=30,
                    ),
                ),
                ("qualification", models.CharField(blank=True, max_length=200)),
                ("verified", models.BooleanField(default=False)),
                ("available", models.BooleanField(default=True)),
                ("service_area", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
