# Generated by Django 6.1.1 on 2026-10-06 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0007_serviceprovider"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebooking",
            name="assigned_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_bookings",
                to="care.serviceprovider",
            ),
        ),
    ]
